services:
  kahawatein:
    image: kahawatein:latest
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
  redis:
    image: redis:latest
    ports:
      - 6379:6379